### ISSUE TITLE
Licence missing

### ISSUE THREAD

**Issue by puntofisso** [Momciloo/fun-with-sockets#1]
Hi there, it would be great if you could add a licence this code – the more open, the better, but that is your choice :-)

**Comment by Momciloo** [comment]
That's a good point @puntofisso. Added the MIT license
https://github.com/Momciloo/fun-with-sockets/blob/main/LICENSE

**Comment by Momciloo** [comment]
That's a good point @puntofisso . Added the MIT license
https://github.com/Momciloo/fun-with-sockets/blob/main/LICENSE
